[dev]
  targetPort=5173
  [build]
   base = "/"
  command = "npm run build"  
  functions = "netlify/functions"
  publish = "dist" 
  
  [[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

  [[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

